// Astro integration that writes `vercel.json`'s security headers from the actual built output
// (03-platform-architecture.md §8; threat-model.md TH-04, TH-06). Runs on the `astro:build:done`
// hook, after every file is written to `dist/`, so the Content Security Policy's `script-src`
// hashes always match the two theme-toggle scripts (src/modules/layout/BaseLayout.astro) as
// shipped: edit one character of either script and the next `pnpm build` writes the new hash
// automatically (T-017 AC5). `vercel.json` is fully generated by this integration; do not hand-edit
// it, since the next build overwrites it.
import { createHash } from "node:crypto";
import { readdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import type { AstroIntegration } from "astro";

// The only third-party script the site loads (src/modules/analytics/Analytics.astro, ADR-008).
const UMAMI_SCRIPT_ORIGIN = "https://cloud.umami.is";

// Analytics.astro's <script> tag sets no `data-host-url`, so Umami's script.js falls back to its
// default collector origin for the page-view POST (`${data-host-url || "https://gateway.umami.is"}
// /api/send`), which differs from the script's own origin above. Both must be allowed in
// connect-src or every page view is blocked by the CSP (B-004).
const UMAMI_COLLECTOR_ORIGIN = "https://gateway.umami.is";

// The two theme-toggle inline scripts in BaseLayout.astro (head + pre-</body>). If a third
// distinct inline <script> ever appears in the build, that is either a mistake or a new first-party
// script this integration does not yet allowlist, so the build must fail loudly rather than ship a
// silently permissive or stale policy.
const EXPECTED_INLINE_SCRIPT_COUNT = 2;

async function listHtmlFiles(dir: string): Promise<string[]> {
  const entries = await readdir(dir, { withFileTypes: true });
  const files: string[] = [];
  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      files.push(...(await listHtmlFiles(fullPath)));
    } else if (entry.name.endsWith(".html")) {
      files.push(fullPath);
    }
  }
  return files;
}

// Matches <script>...</script> elements with no `src` attribute (Astro's `is:inline` scripts
// render with no other identifying marker in the final HTML).
const INLINE_SCRIPT_PATTERN =
  /<script(?![^>]*\ssrc=)[^>]*>([\s\S]*?)<\/script>/gi;

function extractInlineScripts(html: string): string[] {
  const scripts: string[] = [];
  for (const match of html.matchAll(INLINE_SCRIPT_PATTERN)) {
    scripts.push(match[1]);
  }
  return scripts;
}

function sha256Base64(source: string): string {
  return createHash("sha256").update(source, "utf8").digest("base64");
}

async function collectInlineScriptHashes(distDir: string): Promise<string[]> {
  const htmlFiles = await listHtmlFiles(distDir);
  const hashes = new Set<string>();
  for (const file of htmlFiles) {
    const html = await readFile(file, "utf8");
    for (const script of extractInlineScripts(html)) {
      hashes.add(sha256Base64(script));
    }
  }
  return [...hashes].sort();
}

function buildContentSecurityPolicy(scriptHashes: string[]): string {
  const scriptSources = [
    ...scriptHashes.map((hash) => `'sha256-${hash}'`),
    UMAMI_SCRIPT_ORIGIN,
  ].join(" ");
  const directives = [
    "default-src 'self'",
    `script-src ${scriptSources}`,
    // Shiki's syntax-highlighted code blocks (astro.config.ts markdown.shikiConfig) render each
    // token's color as an inline `style` attribute; AC1 only restricts script-src, so style-src
    // keeps 'unsafe-inline' rather than hashing every token combination.
    "style-src 'self' 'unsafe-inline'",
    "img-src 'self' data:",
    "font-src 'self'",
    `connect-src 'self' ${UMAMI_SCRIPT_ORIGIN} ${UMAMI_COLLECTOR_ORIGIN}`,
    "object-src 'none'",
    "base-uri 'self'",
    "form-action 'self'",
    "frame-ancestors 'none'",
  ];
  return `${directives.join("; ")};`;
}

function buildVercelConfig(csp: string): object {
  return {
    headers: [
      {
        source: "/(.*)",
        headers: [
          { key: "Content-Security-Policy", value: csp },
          { key: "X-Content-Type-Options", value: "nosniff" },
          { key: "Referrer-Policy", value: "strict-origin-when-cross-origin" },
          {
            key: "Permissions-Policy",
            value: "camera=(), microphone=(), geolocation=()",
          },
          // Belt-and-braces with the CSP's frame-ancestors 'none' above (AC4): older browsers
          // that don't support frame-ancestors still get denied framing via X-Frame-Options.
          { key: "X-Frame-Options", value: "DENY" },
        ],
      },
    ],
  };
}

export function securityHeadersIntegration(): AstroIntegration {
  return {
    name: "security-headers",
    hooks: {
      "astro:build:done": async ({ dir, logger }) => {
        const distDir = fileURLToPath(dir);
        const scriptHashes = await collectInlineScriptHashes(distDir);

        if (scriptHashes.length !== EXPECTED_INLINE_SCRIPT_COUNT) {
          throw new Error(
            `security-headers: expected exactly ${EXPECTED_INLINE_SCRIPT_COUNT} distinct inline ` +
              `<script> blocks in the build (the theme-toggle scripts), found ` +
              `${scriptHashes.length}: ${scriptHashes.join(", ") || "(none)"}. If a new ` +
              `first-party inline script was added intentionally, update security-headers.ts.`,
          );
        }

        const csp = buildContentSecurityPolicy(scriptHashes);
        const vercelConfig = buildVercelConfig(csp);
        const vercelJsonPath = fileURLToPath(
          new URL("./vercel.json", import.meta.url),
        );

        await writeFile(
          vercelJsonPath,
          `${JSON.stringify(vercelConfig, null, 2)}\n`,
          "utf8",
        );
        logger.info(
          `wrote vercel.json (${scriptHashes.length} script-src hashes)`,
        );
      },
    },
  };
}
